require: rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Rails/TimeZone:
  Enabled: false